<a href="https://colab.research.google.com/github/Kishore192/python/blob/main/functions%26numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a function to accept two numbers as input from the user and display the summation of the numbers

In [ ]:
def sum(a,b):

  c=a+b

  print(c)

In [ ]:
sum(10,20)

30


In [ ]:
sum(-10,-9)

-19


In [ ]:
sum(4,8)

12


In [ ]:
sum(-7,9)

2


In [ ]:
sum(10,20,45)

TypeError: ignored

In [ ]:
sum(10)

TypeError: ignored

In [ ]:
def add(a,b,c):
  e=a+b+c
  print(e)

In [ ]:
add(4,5,7)

16


In [ ]:
add(-5,6,9)

10


Create a function to accept two numbers as input from the user and display the float division of the numbers

In [ ]:
def div(a,b):
  c=a/b
  print(c)

In [ ]:
div(10,2)

5.0


Create a function to accept two numbers as input from the user and display the summation, subtraction, multiplication and division of the numbers

In [ ]:
def compute(p,q):
  e=p+q
  f=p-q
  g=p*q
  h=p/q

  print(e,f,g,h)

In [ ]:
compute(12,10)

22 2 120 1.2


Create a function which accepts 'name' and 'age' of a person and display the name of the person

In [ ]:
def info(name,age):
  print("Hi",name,"good evening :)")

In [ ]:
info('Meera',27)

Hi Meera good evening :)


In [ ]:
info('Ravi',32)

Hi Ravi good evening :)


Create a function which accepts 'name' and 'salary' of a person and display the name and the salary of the person

In [ ]:
def data(name,salary):
  print("Hi",name,"your salary is",salary,"rupees")

In [ ]:
data('George',20000)

Hi George your salary is 20000 rupees


In [ ]:
data('Aashu',)

TypeError: ignored

Create a function which accepts 'name' and 'salary' of a person and display the name and the salary of the person

If the salary of the person is not mentioned, use dafault salary as 10000

In [ ]:
def data(name,salary=10000): #10000 is the default parameter
  print("Hi",name,"your salary is",salary,"rupees")

In [ ]:
data('Aashu',20000)

Hi Aashu your salary is 20000 rupees


In [ ]:
data('Aashu',)

Hi Aashu your salary is 10000 rupees


Create a function which computes the area and circumference of a circle 

In [ ]:
#circumference - 2*pi*r
#area - pi*r^2

def circle(r):
  area=3.14*r**2
  circum=2*3.14*r
  print("area of circle is",area,"units and circumference is",circum,"units")

In [ ]:
circle(4)

area of circle is 50.24 units and circumference is 25.12 units


In [ ]:
circle(15)

area of circle is 706.5 units and circumference is 94.2 units


Create a function which computes area and perimeter of a rectangle

In [ ]:
#area - l*b
#perimeter - 2(l+b)

def rect(l,b):
  area=l*b
  perimeter=2*(l+b)
  print("area of rectange is",area,"units and perimeter is",perimeter,"units")

In [ ]:
rect(10,20)

area of rectange is 200 units and perimeter is 60 units



Create a function to accept three numbers as input from the user and display the largest number out of the three given numbers 

In [ ]:
def max(a,b,c):

  if a>b and a>c:
    print("a is largest")

  elif b>a and b>c:
    print("b is largest")

  else:
    print("c is largest")

In [ ]:
max(4,6,8)

c is largest


In [ ]:
max(45,78,12)

b is largest


Create a function which adds all the elements given in a group of numbers

In [ ]:
def add_sum(num):
  sum=0

  for i in num:
    sum=sum+i

  print(sum)

In [ ]:
add_sum((1,2,3,4,5,6,8,7))

36


In [ ]:
add_sum((2,4,6))

12


In [ ]:
add_sum((2,3,4,5))

14


Create a function which counts the number of vowels and consonants in a given word

In [ ]:
def count(word):
  vowel_count=0
  cons_count=0

  for i in word:
    if i in ('a','A','e','E','i','I','o','O','u','U'):
      vowel_count=vowel_count+1

    else:
      cons_count=cons_count+1

  print("number of vowels are",vowel_count,"and number of consonants",cons_count)

In [ ]:
count('Aashutosh')

number of vowels are 4 and number of consonants 5


In [ ]:
count('Meera')

number of vowels are 3 and number of consonants 2


Create a function which displays the even numbers given in a list of numbers in a new separate list

In [ ]:
#o/p should be a list with all the even numbers from the given list of numbers as i/p

NUMPY

In [ ]:
import numpy as np #np is the alias name

In [ ]:
my_list=[1,2,4,5,6]

In [ ]:
type(my_list)

list

In [ ]:
#converting list into an array
arr=np.array(my_list) #np.array() will convert list into an array

In [ ]:
print(arr)

[1 2 4 5 6]


In [ ]:
type(arr) #ndimentionalarray where n=1, 1darray

numpy.ndarray

In [ ]:
#multinested array
my_list_1=[1,2,4,5,6]
my_list_2=[4,5,6,11,0]
my_list_3=[21,44,58,16,12]

In [ ]:
arr_new=np.array([my_list_1,my_list_2,my_list_3])

In [ ]:
print(arr_new)

[[ 1  2  4  5  6]
 [ 4  5  6 11  0]
 [21 44 58 16 12]]


In [ ]:
arr_new.shape #here 3 indicates number of rows and 5 indicates number of columns

(3, 5)

In [ ]:
arr_new.reshape(5,3) #changes the shape to 5 rows and 3 columns(matrix transpose)

array([[ 1,  2,  4],
       [ 5,  6,  4],
       [ 5,  6, 11],
       [ 0, 21, 44],
       [58, 16, 12]])

In [ ]:
arr_new.reshape(5,4)

ValueError: ignored

In [ ]:
type(arr_new) #2darray

numpy.ndarray

In [ ]:
#indexing

In [ ]:
print(arr)

[1 2 4 5 6]


In [ ]:
arr[3]

5

In [ ]:
arr[4]

6

In [ ]:
print(arr_new)

[[ 1  2  4  5  6]
 [ 4  5  6 11  0]
 [21 44 58 16 12]]


In [ ]:
arr_new[1:4]

array([[ 4,  5,  6, 11,  0],
       [21, 44, 58, 16, 12]])

In [ ]:
print(arr_new)

[[ 1  2  4  5  6]
 [ 4  5  6 11  0]
 [21 44 58 16 12]]


In [ ]:
arr_new[1:,1:]

array([[ 5,  6, 11,  0],
       [44, 58, 16, 12]])

In [ ]:
arr_new[1:4,1:2]

array([[ 5],
       [44]])

In [ ]:
#generating random numbers

In [ ]:
arr_1=np.arange(1,10) #equally spaced values from 1 to 9 (10 will be  exclusive)

In [ ]:
print(arr_1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr_2=np.arange(1,20,2) #2 is the step size 

In [ ]:
print(arr_2)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
np.linspace(1,10,50) #here 50 indicates the number of elements we want in the range(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(1,10,70)

array([ 1.        ,  1.13043478,  1.26086957,  1.39130435,  1.52173913,
        1.65217391,  1.7826087 ,  1.91304348,  2.04347826,  2.17391304,
        2.30434783,  2.43478261,  2.56521739,  2.69565217,  2.82608696,
        2.95652174,  3.08695652,  3.2173913 ,  3.34782609,  3.47826087,
        3.60869565,  3.73913043,  3.86956522,  4.        ,  4.13043478,
        4.26086957,  4.39130435,  4.52173913,  4.65217391,  4.7826087 ,
        4.91304348,  5.04347826,  5.17391304,  5.30434783,  5.43478261,
        5.56521739,  5.69565217,  5.82608696,  5.95652174,  6.08695652,
        6.2173913 ,  6.34782609,  6.47826087,  6.60869565,  6.73913043,
        6.86956522,  7.        ,  7.13043478,  7.26086957,  7.39130435,
        7.52173913,  7.65217391,  7.7826087 ,  7.91304348,  8.04347826,
        8.17391304,  8.30434783,  8.43478261,  8.56521739,  8.69565217,
        8.82608696,  8.95652174,  9.08695652,  9.2173913 ,  9.34782609,
        9.47826087,  9.60869565,  9.73913043,  9.86956522, 10.  

In [ ]:
np.linspace(1,10,70,dtype='int')

array([ 1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  3,
        3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,
        5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
        7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,
        9, 10])

In [ ]:
np.linspace(1,50,30)

array([ 1.        ,  2.68965517,  4.37931034,  6.06896552,  7.75862069,
        9.44827586, 11.13793103, 12.82758621, 14.51724138, 16.20689655,
       17.89655172, 19.5862069 , 21.27586207, 22.96551724, 24.65517241,
       26.34482759, 28.03448276, 29.72413793, 31.4137931 , 33.10344828,
       34.79310345, 36.48275862, 38.17241379, 39.86206897, 41.55172414,
       43.24137931, 44.93103448, 46.62068966, 48.31034483, 50.        ])

In [ ]:
np.linspace(1,50,30, dtype='int')

array([ 1,  2,  4,  6,  7,  9, 11, 12, 14, 16, 17, 19, 21, 22, 24, 26, 28,
       29, 31, 33, 34, 36, 38, 39, 41, 43, 44, 46, 48, 50])

In [ ]:
np.random.rand(3,4) #here 3 is the number of rows and 4 is the number of columns 
#by default the range in random.rand is 0-1 (1 being exclusive)

array([[0.95687084, 0.8679445 , 0.44902711, 0.21301547],
       [0.70225019, 0.4285725 , 0.60057049, 0.0885588 ],
       [0.23575742, 0.08072196, 0.10946011, 0.4058795 ]])

In [ ]:
np.random.rand(3,5)

array([[0.68262766, 0.99042536, 0.33108943, 0.09204186, 0.21883495],
       [0.67948116, 0.19445457, 0.40957607, 0.34405706, 0.75357368],
       [0.98839799, 0.82313992, 0.48085116, 0.38069627, 0.5826579 ]])

In [ ]:
np.random.randint(3,9,4) #here 3-9 is the range and 4 indicates the number of elements we want from this range

array([6, 4, 8, 3])

In [ ]:
np.random.randint(1,20,5)

array([ 8,  8, 12,  2, 15])